name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-commands:
    name: Build Commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build commands
      - run: mkdir -p ~/dotfiles-install-dir && HOME=~/dotfiles-install-dir ./install --only shell

  build-links:
    name: Build Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build links
        run: mkdir -p ~/dotfiles-install-dir && HOME=~/dotfiles-install-dir ./install --only links

  build-all:
    name: Build all
    needs: [ build-commands, build-links ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build all
        run: mkdir -p ~/dotfiles-install-dir && HOME=~/dotfiles-install-dir ./install
