name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p ~/dotfiles-install-dir && HOME=~/dotfiles-install-dir ./install --only shell
        name: Build commands
      - uses: actions/checkout@v2
      - run: mkdir -p ~/dotfiles-install-dir && HOME=~/dotfiles-install-dir ./install --only links
        name: Build links
      - uses: actions/checkout@v2
      - run: mkdir -p ~/dotfiles-install-dir && HOME=~/dotfiles-install-dir ./install
        name: Build all
